"""
======================================================================
CLASSIFIC-AI

Feature Quality Module

Purpose
-------
Evaluates the overall quality of every feature using the outputs
generated by previous profiling modules.

Responsibilities
----------------
• Evaluate missing value quality
• Evaluate variance quality
• Evaluate cardinality quality
• Evaluate distribution quality
• Calculate overall feature quality score
• Generate feature-level recommendation

Future Enhancements
-------------------
Version 1.1
• AI Feature Scoring
• Business Importance Weighting
• Target Leakage Detection

Version 2.0
• Explainable AI Feature Assessment
• LLM-powered Recommendations
• RAG Knowledge Integration

Author : Biswadip Choudhury
Version : 1.0.0
======================================================================
"""

import pandas as pd


class FeatureQuality:

    def analyze(self, df: pd.DataFrame):

        ###############################################################
        # Start
        ###############################################################

        print()
        print("=" * 70)
        print("FEATURE QUALITY")
        print("=" * 70)

        feature_quality_information = []

        ###############################################################
        # Analyze Every Column
        ###############################################################

        for column in df.columns:

            ###########################################################
            # Detect Data Type
            ###########################################################

            if pd.api.types.is_numeric_dtype(df[column]):

                data_type = "Numeric"

            elif pd.api.types.is_datetime64_any_dtype(df[column]):

                data_type = "Datetime"

            elif pd.api.types.is_bool_dtype(df[column]):

                data_type = "Boolean"

            else:

                data_type = "Categorical"

            ###########################################################
            # Missing Value Quality
            ###########################################################

            missing_percent = (
                df[column].isnull().sum() /
                len(df)
            ) * 100

            if missing_percent == 0:

                missing_quality = "Excellent"

            elif missing_percent < 5:

                missing_quality = "Good"

            elif missing_percent < 20:

                missing_quality = "Needs Review"

            else:

                missing_quality = "Poor"

            ###########################################################
            # Placeholders
            ###########################################################

            variance_quality = "Pending"

            cardinality_quality = "Pending"

            distribution_quality = "Pending"

            overall_score = 0

            feature_quality = "Pending"

            recommendation = "Pending"

            ###########################################################
            # Numeric Feature Assessment
            ###########################################################

            if data_type == "Numeric":

                variance = df[column].var()

                skewness = df[column].skew()

                if variance == 0:

                    variance_quality = "Poor"

                elif variance < 0.01:

                    variance_quality = "Needs Review"

                else:

                    variance_quality = "Good"

                if abs(skewness) < 1:

                    distribution_quality = "Good"

                else:

                    distribution_quality = "Needs Review"

            ###########################################################
            # Categorical Feature Assessment
            ###########################################################

            else:

                unique = df[column].nunique(dropna=True)

                cardinality_percent = (unique / len(df)) * 100

                if cardinality_percent < 5:

                    cardinality_quality = "Good"

                elif cardinality_percent < 20:

                    cardinality_quality = "Needs Review"

                else:

                    cardinality_quality = "Poor"

            ###########################################################
            # Overall Feature Score
            ###########################################################

            overall_score = 100

            if missing_quality == "Good":

                overall_score -= 5

            elif missing_quality == "Needs Review":

                overall_score -= 15

            elif missing_quality == "Poor":

                overall_score -= 30

            if variance_quality == "Needs Review":

                overall_score -= 10

            elif variance_quality == "Poor":

                overall_score -= 20

            if cardinality_quality == "Needs Review":

                overall_score -= 10

            elif cardinality_quality == "Poor":

                overall_score -= 20

            if distribution_quality == "Needs Review":

                overall_score -= 10

            ###########################################################
            # Final Rating
            ###########################################################

            if overall_score >= 90:

                feature_quality = "Excellent"

            elif overall_score >= 75:

                feature_quality = "Good"

            elif overall_score >= 60:

                feature_quality = "Needs Review"

            else:

                feature_quality = "Poor"

            ###########################################################
            # Recommendation
            ###########################################################

            if feature_quality == "Excellent":

                recommendation = "Ready for modeling."

            elif feature_quality == "Good":

                recommendation = "Minor preprocessing recommended."

            elif feature_quality == "Needs Review":

                recommendation = "Investigate feature before modeling."

            else:

                recommendation = "Consider removing or transforming feature."

            ###########################################################
            # Terminal Output
            ###########################################################

            print("-" * 60)

            print(f"Column                 : {column}")

            print(f"Data Type              : {data_type}")

            print(f"Missing Quality        : {missing_quality}")

            print(f"Variance Quality       : {variance_quality}")

            print(f"Cardinality Quality    : {cardinality_quality}")

            print(f"Distribution Quality   : {distribution_quality}")

            print(f"Overall Score          : {overall_score}")

            print(f"Feature Quality        : {feature_quality}")

            print(f"Recommendation         : {recommendation}")

            ###########################################################
            # Store Results
            ###########################################################

            feature_quality_information.append({

                "column_name": column,

                "data_type": data_type,

                "missing_quality": missing_quality,

                "variance_quality": variance_quality,

                "cardinality_quality": cardinality_quality,

                "distribution_quality": distribution_quality,

                "overall_score": overall_score,

                "feature_quality": feature_quality,

                "recommendation": recommendation

            })

        ###############################################################
        # Return Results
        ###############################################################

        return {

            "module": "Feature Quality",

            "status": "Completed",

            "feature_quality": feature_quality_information

        }