"""
==============================================================
CLASSIFIC-AI
Recommendation Engine Module

Author : Biswadip Choudhury
Version : 2.0.0

Purpose
-------
This module combines the outputs of every preprocessing
module and produces one intelligent preprocessing plan.

The module does NOT analyze the dataframe directly.

Instead it consumes the results generated by

✓ Duplicate Module
✓ Missing Value Module
✓ DataType Module
✓ Outlier Module
✓ Encoding Module
✓ Scaling Module
✓ Date Module
✓ Text Module
✓ Boolean Module
✓ Constant Feature Module
✓ High Cardinality Module
✓ ID Detection Module

Features
--------
• Dataset Health Summary
• Intelligent Recommendations
• Ordered Preprocessing Pipeline
• Human Approval Detection
• Dataset Readiness Score

Future Version
--------------
• Cost estimation
• Time estimation
• Auto Pipeline Builder
• LLM Explanation
==============================================================
"""

import pandas as pd

class RecommendationEngine:

    def analyze(
        self,
        df: pd.DataFrame,
        duplicate_result,
        missing_value_result,
        datatype_result,
        outlier_result,
        encoding_result,
        scaling_result,
        date_result,
        text_result,
        boolean_result,
        constant_feature_result,
        high_cardinality_result,
        id_detection_result
    ):
        
        ##############################################################
        # Initialize Variables
        ##############################################################

        recommendations = []

        preprocessing_steps = []

        human_approval = False

        dataset_health_score = 100

        issues_detected = []

        summary = {}

        readiness_status = ""

        ##############################################################
        # Duplicate Module
        ##############################################################

        duplicate_count = duplicate_result["summary"]["duplicate_rows"]

        if duplicate_count > 0:

            issues_detected.append("Duplicate Rows")

            recommendations.append(
                f"Remove {duplicate_count} duplicate rows."
            )

            preprocessing_steps.append(
                "Remove duplicate rows"
            )

            dataset_health_score -= 10

        ##############################################################
        # Missing Value Module
        ##############################################################

        missing_columns = missing_value_result["summary"]["columns_with_missing"]

        if missing_columns > 0:

            issues_detected.append("Missing Values")

            recommendations.append(
                "Impute missing values before model training."
            )

            preprocessing_steps.append(
                "Handle missing values"
            )

            dataset_health_score -= 10

        ##############################################################
        # Constant Feature Module
        ##############################################################

        constant_columns = constant_feature_result["summary"]["Constant Columns"]

        if constant_columns > 0:

            issues_detected.append("Constant Features")

            recommendations.append(
                "Remove constant feature columns."
            )

            preprocessing_steps.append(
                "Remove constant features"
            )

            dataset_health_score -= 10

        ##############################################################
        # High Cardinality Module
        ##############################################################

        high_cardinality_columns = high_cardinality_result["summary"]["High Cardinality Columns"]

        if high_cardinality_columns > 0:

            issues_detected.append("High Cardinality")

            recommendations.append(
                "Apply Frequency Encoding, Target Encoding or Embeddings."
            )

            preprocessing_steps.append(
                "Encode high-cardinality columns"
            )

            dataset_health_score -= 10

        ##############################################################
        # ID Detection Module
        ##############################################################

        id_columns = id_detection_result["summary"]["ID Columns"]

        if id_columns > 0:

            issues_detected.append("Identifier Columns")

            recommendations.append(
                "Remove identifier columns before model training."
            )

            preprocessing_steps.append(
                "Drop identifier columns"
            )

            dataset_health_score -= 10

        ##############################################################
        # Dataset Readiness
        ##############################################################

        if dataset_health_score >= 90:

            readiness_status = "Excellent"

        elif dataset_health_score >= 75:

            readiness_status = "Good"

        elif dataset_health_score >= 50:

            readiness_status = "Fair"

        else:

            readiness_status = "Poor"

        ##############################################################
        # Human Approval
        ##############################################################

        modules = [

            duplicate_result,

            missing_value_result,

            datatype_result,

            outlier_result,

            encoding_result,

            scaling_result,

            date_result,

            text_result,

            boolean_result,

            constant_feature_result,

            high_cardinality_result,

            id_detection_result

        ]

        for module in modules:

            if module["human_approval_required"]:

                human_approval = True

                break

        ##############################################################
        # Summary
        ##############################################################

        summary = {

            "Dataset Health Score": dataset_health_score,

            "Readiness Status": readiness_status,

            "Issues Detected": len(issues_detected),

            "Recommendations": len(recommendations),

            "Human Approval": human_approval

        }

        ##############################################################
        # Result
        ##############################################################

        result = {

            "summary": summary,

            "recommendations": recommendations,

            "preprocessing_steps": preprocessing_steps,

            "issues_detected": issues_detected,

            "dataset_health_score": dataset_health_score,

            "readiness_status": readiness_status,

            "human_approval_required": human_approval,

            "dataframe": df

        }

        return result
    


